// <auto-generated />
using ControlGastos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable
namespace ControlGastos.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder mb)
    {
#pragma warning disable 612, 618
        mb.HasAnnotation("ProductVersion", "8.0.0")
          .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(mb);

        mb.Entity("ControlGastos.Models.CategoriaGasto", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<string>("Nombre").IsRequired().HasMaxLength(80).HasColumnType("nvarchar(80)");
            b.Property<string>("Tipo").IsRequired().HasColumnType("nvarchar(max)");
            b.HasKey("Id");
            b.ToTable("CategoriasGasto");
        });

        mb.Entity("ControlGastos.Models.GastoItem", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<int>("Anio").HasColumnType("int");
            b.Property<int>("CantidadPersonas").HasColumnType("int");
            b.Property<int>("CategoriaId").HasColumnType("int");
            b.Property<string>("Descripcion").HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<int>("Dia").HasColumnType("int");
            b.Property<string>("MedioPago").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<int>("Mes").HasColumnType("int");
            b.Property<decimal>("Monto").HasPrecision(18,2).HasColumnType("decimal(18,2)");
            b.Property<decimal?>("MontoDividido").HasPrecision(18,2).HasColumnType("decimal(18,2)");
            b.Property<bool>("SeDivide").HasColumnType("bit");
            b.Property<int?>("TarjetaCuotaId").HasColumnType("int");
            b.HasKey("Id");
            b.HasIndex("CategoriaId");
            b.HasIndex("TarjetaCuotaId");
            b.ToTable("Gastos");
        });

        mb.Entity("ControlGastos.Models.Ingreso", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<int>("Anio").HasColumnType("int");
            b.Property<string>("Descripcion").HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<int>("Dia").HasColumnType("int");
            b.Property<string>("Fuente").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<int>("Mes").HasColumnType("int");
            b.Property<decimal>("Monto").HasPrecision(18,2).HasColumnType("decimal(18,2)");
            b.Property<string>("Tipo").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.ToTable("Ingresos");
        });

        mb.Entity("ControlGastos.Models.Tarjeta", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<string>("Banco").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)");
            b.Property<int>("DiaCierre").HasColumnType("int");
            b.Property<int>("DiaVencimiento").HasColumnType("int");
            b.Property<string>("Nombre").IsRequired().HasMaxLength(60).HasColumnType("nvarchar(60)");
            b.Property<string>("Red").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.HasKey("Id");
            b.ToTable("Tarjetas");
        });

        mb.Entity("ControlGastos.Models.TarjetaCuota", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<int>("AnioCierre").HasColumnType("int");
            b.Property<string>("Comercio").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
            b.Property<int>("CuotasPagadas").HasColumnType("int");
            b.Property<DateTime>("FechaCompra").HasColumnType("datetime2");
            b.Property<int>("MesCierre").HasColumnType("int");
            b.Property<decimal>("MontoCuota").HasPrecision(18,2).HasColumnType("decimal(18,2)");
            b.Property<decimal?>("MontoPagoOtro").HasPrecision(18,2).HasColumnType("decimal(18,2)");
            b.Property<decimal>("MontoTotal").HasPrecision(18,2).HasColumnType("decimal(18,2)");
            b.Property<string>("PagaParte").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)");
            b.Property<int>("TarjetaId").HasColumnType("int");
            b.Property<int>("TotalCuotas").HasColumnType("int");
            b.HasKey("Id");
            b.HasIndex("TarjetaId");
            b.ToTable("TarjetaCuotas");
        });

        mb.Entity("ControlGastos.Models.Cuenta", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<int>("Anio").HasColumnType("int");
            b.Property<int>("Mes").HasColumnType("int");
            b.Property<string>("Nombre").IsRequired().HasMaxLength(60).HasColumnType("nvarchar(60)");
            b.Property<decimal>("SaldoFinal").HasPrecision(18,2).HasColumnType("decimal(18,2)");
            b.Property<decimal>("SaldoInicio").HasPrecision(18,2).HasColumnType("decimal(18,2)");
            b.HasKey("Id");
            b.ToTable("Cuentas");
        });

        mb.Entity("ControlGastos.Models.Deuda", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<string>("Descripcion").HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<string>("Direccion").IsRequired().HasColumnType("nvarchar(max)");
            b.Property<string>("Estado").IsRequired().HasColumnType("nvarchar(max)");
            b.Property<DateTime>("Fecha").HasColumnType("datetime2");
            b.Property<decimal>("Monto").HasPrecision(18,2).HasColumnType("decimal(18,2)");
            b.Property<decimal?>("MontoPagado").HasPrecision(18,2).HasColumnType("decimal(18,2)");
            b.Property<string>("Persona").IsRequired().HasMaxLength(80).HasColumnType("nvarchar(80)");
            b.HasKey("Id");
            b.ToTable("Deudas");
        });

        mb.Entity("ControlGastos.Models.EfectivoDesglose", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<int>("Anio").HasColumnType("int");
            b.Property<int>("Cantidad").HasColumnType("int");
            b.Property<int>("Denominacion").HasColumnType("int");
            b.Property<int>("Mes").HasColumnType("int");
            b.HasKey("Id");
            b.ToTable("EfectivoDesgloses");
        });

        mb.Entity("ControlGastos.Models.GastoItem", b =>
        {
            b.HasOne("ControlGastos.Models.CategoriaGasto","Categoria")
             .WithMany("Gastos").HasForeignKey("CategoriaId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.HasOne("ControlGastos.Models.TarjetaCuota","TarjetaCuota")
             .WithMany("GastosAsociados").HasForeignKey("TarjetaCuotaId").OnDelete(DeleteBehavior.SetNull);
        });

        mb.Entity("ControlGastos.Models.TarjetaCuota", b =>
        {
            b.HasOne("ControlGastos.Models.Tarjeta","Tarjeta")
             .WithMany("Cuotas").HasForeignKey("TarjetaId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        });
#pragma warning restore 612, 618
    }
}
